#!/usr/bin/env python3
# bilinear_mc_ref.py — spec-literal reference for AV1 motion compensation, covering the
# BILINEAR interpolation filter (spec 7.11.3.4) and, as its own validation, the whole
# unscaled single-reference translation MC path that drishti's av1_mc_pred_block implements.
# The oracle for the BILINEAR known answers; never back-derived from the Cyrius.
#
# THIS PORT IS DELIBERATELY IN THE **SPEC** CONVENTION, NOT DRISHTI'S.
#
# drishti carries dav1d's table: 15 phases, rows summing to 64, with every kernel round one
# bit SMALLER. The spec's is 16 phases, rows summing to 128. Writing the oracle in the spec
# convention makes it a genuine CROSS-CONVENTION check: if the two agree pixel-for-pixel,
# the halving-plus-reduced-shift equivalence is PROVEN by the test rather than assumed by a
# comment. The equivalence rests on two facts, both checked here rather than asserted:
#   (1) Round2(2*s, n) == Round2(s, n-1) for an ARITHMETIC shift, and
#   (2) every spec tap is even (verify_against_spec asserts it over all 768 values).
#
# SET INDEX PERMUTATION (spec -> dav1d/drishti), asserted by verify_against_spec():
#   spec 0 REGULAR   -> drishti 0        spec 3 BILINEAR    -> drishti 5
#   spec 1 SMOOTH    -> drishti 1        spec 4 REGULAR/4   -> drishti 3
#   spec 2 SHARP     -> drishti 2        spec 5 SMOOTH/4    -> drishti 4
#
# THE SELECTION RULE (spec 7.11.3.4, quoted verbatim from the fetched spec):
#     interpFilter = InterpFilters[ candRow ][ candCol ][ 1 ]
#     if ( w <= 4 ) {
#         if ( interpFilter == EIGHTTAP || interpFilter == EIGHTTAP_SHARP ) {
#             interpFilter = 4
#         } else if ( interpFilter == EIGHTTAP_SMOOTH ) {
#             interpFilter = 5
#         }
#     }
# There is NO `else` branch: BILINEAR (3) falls through UNCHANGED at every block extent. That
# is why drishti's av1_mc_filter_set must test `f == 3` BEFORE its `dim <= 4` remap. Getting
# that order wrong turns a 4-wide bilinear block into 4-tap SMOOTH — wrong pixels, no error.
#
# SELF-VALIDATION: main() first re-derives the SEVENTEEN pre-existing non-bilinear driver
# known answers (c01..c16 in tests/av1_mc_driver.tcyr, originally generated by the long-lost
# scratchpad mc_driver_ref.py) and only then prints the new BILINEAR rows. A port that
# reproduces 17 independently-established goldens is trustworthy for the new ones; this also
# re-establishes the provenance those tests lost when the scratchpad was wiped (see
# scripts/refs/README.md, "Why these live in the repo").
#
# Source: AOMediaCodec/av1-spec master 08.decoding.process.md,
#         md5 51249ad97e9fd97dc3b0dc0e14de83b0 (fetched 2026-07-19), sections 7.11.3.2/3/4.

SPEC_MD5 = "51249ad97e9fd97dc3b0dc0e14de83b0"

SPEC_BILINEAR_SET = 3       # index into the spec's Subpel_Filters
DRISHTI_BILINEAR_SET = 5    # index into drishti's av1_subpel_filter
# spec set index -> drishti/dav1d set index
PERM = {0: 0, 1: 1, 2: 2, 3: 5, 4: 3, 5: 4}

# MACHINE-GENERATED from the spec markdown (md5 51249ad97e9fd97dc3b0dc0e14de83b0),
# never hand-typed. Regenerate + re-verify with verify_against_spec().
SPEC_SUBPEL_FILTERS = [
    [  # spec set 0 — REGULAR
        [0, 0, 0, 128, 0, 0, 0, 0],
        [0, 2, -6, 126, 8, -2, 0, 0],
        [0, 2, -10, 122, 18, -4, 0, 0],
        [0, 2, -12, 116, 28, -8, 2, 0],
        [0, 2, -14, 110, 38, -10, 2, 0],
        [0, 2, -14, 102, 48, -12, 2, 0],
        [0, 2, -16, 94, 58, -12, 2, 0],
        [0, 2, -14, 84, 66, -12, 2, 0],
        [0, 2, -14, 76, 76, -14, 2, 0],
        [0, 2, -12, 66, 84, -14, 2, 0],
        [0, 2, -12, 58, 94, -16, 2, 0],
        [0, 2, -12, 48, 102, -14, 2, 0],
        [0, 2, -10, 38, 110, -14, 2, 0],
        [0, 2, -8, 28, 116, -12, 2, 0],
        [0, 0, -4, 18, 122, -10, 2, 0],
        [0, 0, -2, 8, 126, -6, 2, 0],
    ],
    [  # spec set 1 — SMOOTH
        [0, 0, 0, 128, 0, 0, 0, 0],
        [0, 2, 28, 62, 34, 2, 0, 0],
        [0, 0, 26, 62, 36, 4, 0, 0],
        [0, 0, 22, 62, 40, 4, 0, 0],
        [0, 0, 20, 60, 42, 6, 0, 0],
        [0, 0, 18, 58, 44, 8, 0, 0],
        [0, 0, 16, 56, 46, 10, 0, 0],
        [0, -2, 16, 54, 48, 12, 0, 0],
        [0, -2, 14, 52, 52, 14, -2, 0],
        [0, 0, 12, 48, 54, 16, -2, 0],
        [0, 0, 10, 46, 56, 16, 0, 0],
        [0, 0, 8, 44, 58, 18, 0, 0],
        [0, 0, 6, 42, 60, 20, 0, 0],
        [0, 0, 4, 40, 62, 22, 0, 0],
        [0, 0, 4, 36, 62, 26, 0, 0],
        [0, 0, 2, 34, 62, 28, 2, 0],
    ],
    [  # spec set 2 — SHARP
        [0, 0, 0, 128, 0, 0, 0, 0],
        [-2, 2, -6, 126, 8, -2, 2, 0],
        [-2, 6, -12, 124, 16, -6, 4, -2],
        [-2, 8, -18, 120, 26, -10, 6, -2],
        [-4, 10, -22, 116, 38, -14, 6, -2],
        [-4, 10, -22, 108, 48, -18, 8, -2],
        [-4, 10, -24, 100, 60, -20, 8, -2],
        [-4, 10, -24, 90, 70, -22, 10, -2],
        [-4, 12, -24, 80, 80, -24, 12, -4],
        [-2, 10, -22, 70, 90, -24, 10, -4],
        [-2, 8, -20, 60, 100, -24, 10, -4],
        [-2, 8, -18, 48, 108, -22, 10, -4],
        [-2, 6, -14, 38, 116, -22, 10, -4],
        [-2, 6, -10, 26, 120, -18, 8, -2],
        [-2, 4, -6, 16, 124, -12, 6, -2],
        [0, 2, -2, 8, 126, -6, 2, -2],
    ],
    [  # spec set 3 — BILINEAR
        [0, 0, 0, 128, 0, 0, 0, 0],
        [0, 0, 0, 120, 8, 0, 0, 0],
        [0, 0, 0, 112, 16, 0, 0, 0],
        [0, 0, 0, 104, 24, 0, 0, 0],
        [0, 0, 0, 96, 32, 0, 0, 0],
        [0, 0, 0, 88, 40, 0, 0, 0],
        [0, 0, 0, 80, 48, 0, 0, 0],
        [0, 0, 0, 72, 56, 0, 0, 0],
        [0, 0, 0, 64, 64, 0, 0, 0],
        [0, 0, 0, 56, 72, 0, 0, 0],
        [0, 0, 0, 48, 80, 0, 0, 0],
        [0, 0, 0, 40, 88, 0, 0, 0],
        [0, 0, 0, 32, 96, 0, 0, 0],
        [0, 0, 0, 24, 104, 0, 0, 0],
        [0, 0, 0, 16, 112, 0, 0, 0],
        [0, 0, 0, 8, 120, 0, 0, 0],
    ],
    [  # spec set 4 — REGULAR/4-tap
        [0, 0, 0, 128, 0, 0, 0, 0],
        [0, 0, -4, 126, 8, -2, 0, 0],
        [0, 0, -8, 122, 18, -4, 0, 0],
        [0, 0, -10, 116, 28, -6, 0, 0],
        [0, 0, -12, 110, 38, -8, 0, 0],
        [0, 0, -12, 102, 48, -10, 0, 0],
        [0, 0, -14, 94, 58, -10, 0, 0],
        [0, 0, -12, 84, 66, -10, 0, 0],
        [0, 0, -12, 76, 76, -12, 0, 0],
        [0, 0, -10, 66, 84, -12, 0, 0],
        [0, 0, -10, 58, 94, -14, 0, 0],
        [0, 0, -10, 48, 102, -12, 0, 0],
        [0, 0, -8, 38, 110, -12, 0, 0],
        [0, 0, -6, 28, 116, -10, 0, 0],
        [0, 0, -4, 18, 122, -8, 0, 0],
        [0, 0, -2, 8, 126, -4, 0, 0],
    ],
    [  # spec set 5 — SMOOTH/4-tap
        [0, 0, 0, 128, 0, 0, 0, 0],
        [0, 0, 30, 62, 34, 2, 0, 0],
        [0, 0, 26, 62, 36, 4, 0, 0],
        [0, 0, 22, 62, 40, 4, 0, 0],
        [0, 0, 20, 60, 42, 6, 0, 0],
        [0, 0, 18, 58, 44, 8, 0, 0],
        [0, 0, 16, 56, 46, 10, 0, 0],
        [0, 0, 14, 54, 48, 12, 0, 0],
        [0, 0, 12, 52, 52, 12, 0, 0],
        [0, 0, 12, 48, 54, 14, 0, 0],
        [0, 0, 10, 46, 56, 16, 0, 0],
        [0, 0, 8, 44, 58, 18, 0, 0],
        [0, 0, 6, 42, 60, 20, 0, 0],
        [0, 0, 4, 40, 62, 22, 0, 0],
        [0, 0, 4, 36, 62, 26, 0, 0],
        [0, 0, 2, 34, 62, 30, 0, 0],
    ],
]


# ---------------------------------------------------------------------------
# Spec primitives (04.conventions.md). Python's >> on ints is ARITHMETIC, which
# is what the spec means by >> (sign-propagating) and what Cyrius spells >>>.
# ---------------------------------------------------------------------------

def round2(x, n):
    if n == 0:
        return x
    return (x + (1 << (n - 1))) >> n


def clip3(lo, hi, v):
    return lo if v < lo else (hi if v > hi else v)


def clip1(v, bd):
    return clip3(0, (1 << bd) - 1, v)


def inter_rounds(bd, is_compound):
    """Spec 7.11.3.2, rounding variables derivation process (quoted at :2889-2897)."""
    r0 = 3
    r1 = 7 if is_compound else 11
    if bd == 12:
        r0 += 2
        if not is_compound:
            r1 -= 2
    post = 2 * 7 - (r0 + r1)          # 2 * FILTER_BITS - (InterRound0 + InterRound1)
    return r0, r1, post


def filter_idx_spec(interp_filter, dim):
    """Spec 7.11.3.4 set selection -> a SPEC set index."""
    f = interp_filter
    if dim <= 4:
        if f == 0 or f == 2:          # EIGHTTAP, EIGHTTAP_SHARP
            f = 4
        elif f == 1:                  # EIGHTTAP_SMOOTH
            f = 5
        # BILINEAR (3): no else branch — unchanged at every extent.
    return f


def filter_idx_drishti(interp_filter, dim):
    """The same rule expressed in drishti's permuted index space."""
    return PERM[filter_idx_spec(interp_filter, dim)]


# ---------------------------------------------------------------------------
# The unscaled geometry reduction of 7.11.3.3, and 7.11.3.4 over it.
# ---------------------------------------------------------------------------

def pos16(x, mv, sub):
    """1/16-pel position of a block edge. mv is 1/8 LUMA pel; sub the plane subsampling.

    For equal reference and current dimensions the full 7.11.3.3 scaling collapses exactly
    to this: xScale == 1 << REF_SCALE_SHIFT, stepX == 1024, and with
    startX = (pos16 << 6) + 32 every sample position p = startX + 1024*c satisfies
        (p >> 10) == (pos16 >> 4) + c        and      (p >> 6) & SUBPEL_MASK == pos16 & 15
    so the halfSample / off rounding terms cancel at both extractions.
    """
    return (x << 4) + ((2 * mv) >> sub)


def fill_val(p, r, c, bd):
    """The shared deterministic plane fill — matches mcd_val() in tests/av1_mc_driver.tcyr."""
    return ((r * 31) + (c * 17) + (((r * c) % 11) * 5) + (p * 29)) % (1 << bd)


def make_plane(p, pw, ph, bd):
    return [[fill_val(p, r, c, bd) for c in range(pw)] for r in range(ph)]


def pred_block(plane, pw, ph, x, y, w, h, mvr, mvc, fx, fy, bd, sub_x, sub_y,
               is_compound=0):
    """Spec 7.11.3.4 over the unscaled geometry. Returns list[h][w]."""
    r0, r1, _post = inter_rounds(bd, is_compound)
    lastX, lastY = pw - 1, ph - 1

    px = pos16(x, mvc, sub_x)
    py = pos16(y, mvr, sub_y)
    ix, mx = px >> 4, px & 15
    iy, my = py >> 4, py & 15

    # Horizontal pass: the H filter is selected by the block WIDTH.
    hset = filter_idx_spec(fx, w)
    ftab_h = SPEC_SUBPEL_FILTERS[hset][mx]
    inter = [[0] * w for _ in range(h + 7)]
    for r in range(h + 7):
        sy = clip3(0, lastY, iy + r - 3)
        for c in range(w):
            s = 0
            for t in range(8):
                sx = clip3(0, lastX, ix + c + t - 3)
                s += ftab_h[t] * plane[sy][sx]
            inter[r][c] = round2(s, r0)

    # Vertical pass: the V filter is selected by the block HEIGHT.
    vset = filter_idx_spec(fy, h)
    ftab_v = SPEC_SUBPEL_FILTERS[vset][my]
    out = [[0] * w for _ in range(h)]
    for r in range(h):
        for c in range(w):
            s = 0
            for t in range(8):
                s += ftab_v[t] * inter[r + t][c]
            v = round2(s, r1)
            out[r][c] = v if is_compound else clip1(v, bd)
    return out


def checksum(block):
    """Position-weighted checksum sum v*(i+1) — matches mcd_cs() in the .tcyr suites."""
    ck = 0
    i = 0
    for row in block:
        for v in row:
            ck += (i + 1) * v
            i += 1
    return ck


def run_case(fw, fh, planes, subx, suby, bd, plane_idx, x, y, w, h, mvr, mvc, fx, fy):
    sx = subx if plane_idx > 0 else 0
    sy = suby if plane_idx > 0 else 0
    pw = (fw + subx) >> subx if plane_idx > 0 else fw
    ph = (fh + suby) >> suby if plane_idx > 0 else fh
    plane = make_plane(plane_idx, pw, ph, bd)
    out = pred_block(plane, pw, ph, x, y, w, h, mvr, mvc, fx, fy, bd, sx, sy)
    return checksum(out), out[0][0], out[h - 1][w - 1]


def verify_against_spec(path):
    """Re-derive Subpel_Filters from the spec markdown and check the embedded copy.

    The embedded table must never be trusted on its own — a hand-typed 8-tuple is exactly
    the failure the 0.7.95 warp-table bite was built to prevent, which is why this one was
    machine-generated. Pass the fetched 08.decoding.process.md.
    """
    import hashlib
    import re

    raw = open(path, "rb").read()
    got = hashlib.md5(raw).hexdigest()
    assert got == SPEC_MD5, "spec md5 drift: %s != %s" % (got, SPEC_MD5)

    txt = raw.decode()
    i = txt.index("where the constant array Subpel_Filters is specified as:")
    blk = txt[i:i + 9000]
    s = blk.index("{")
    e = blk.index("~~~~~", s)
    vals = [int(v) for v in re.findall(r"-?\d+", blk[s:e])]
    assert len(vals) == 768, "expected 768 coefficients, got %d" % len(vals)
    spec = [[vals[(st * 16 + ph) * 8:(st * 16 + ph) * 8 + 8] for ph in range(16)]
            for st in range(6)]
    assert spec == SPEC_SUBPEL_FILTERS, "embedded table != spec"

    for st in range(6):
        assert spec[st][0] == [0, 0, 0, 128, 0, 0, 0, 0], "phase-0 identity (set %d)" % st
        assert all(sum(r) == 128 for r in spec[st]), "row sums (set %d)" % st
        assert all(v % 2 == 0 for r in spec[st] for v in r), "taps even (set %d)" % st

    bil = spec[SPEC_BILINEAR_SET]
    for p, row in enumerate(bil):
        nz = sum(1 for v in row if v != 0)
        assert nz == (1 if p == 0 else 2), "BILINEAR phase %d is not 2-tap: %s" % (p, row)
    return {"md5": got}


def drishti_rows(spec_set):
    """The halved 15-phase rows drishti holds for a given SPEC set (phase 0 dropped)."""
    return [[v // 2 for v in SPEC_SUBPEL_FILTERS[spec_set][p]] for p in range(1, 16)]


# The 17 PRE-EXISTING non-bilinear driver known answers (tests/av1_mc_driver.tcyr
# test_mc_pred_known_answers). Reproducing these validates this port before it is trusted
# for the new BILINEAR rows below.
#          name              fw  fh  pl sx sy  bd  p   x   y   w   h    mvr     mvc  fx fy   cs    first last
EXISTING = [
    ("c01 copy",             24, 18, 3, 1, 1,  8, 0,  4,  3,  8,  8,      0,      0, 0, 0, 300779, 166, 241),
    ("c02 int-mv",           24, 18, 3, 1, 1,  8, 0,  4,  3,  8,  8,     40,    -16, 0, 0, 260369,  51, 121),
    ("c03 h-only",           24, 18, 3, 1, 1,  8, 0,  8,  5,  8,  8,      0,      3, 0, 0, 260523,  66, 144),
    ("c04 v-only",           24, 18, 3, 1, 1,  8, 0,  6,  4,  8,  8,      5,      0, 0, 0, 297019, 114,  70),
    ("c05 hv",               24, 18, 3, 1, 1,  8, 0, 10,  8,  8,  8,    -13,     21, 0, 0, 283279, 164,  94),
    ("c06 tl-overhang",      24, 18, 3, 1, 1,  8, 0,  0,  0,  8,  8,     -9,     -7, 0, 0, 288945,   0,  38),
    ("c07 br-overhang",      24, 18, 3, 1, 1,  8, 0, 16, 10,  8,  8,     60,     50, 0, 0, 366794, 146, 180),
    ("c08 wholly-out",       24, 18, 3, 1, 1,  8, 0,  8,  8,  8,  8,      0,    512, 0, 0, 210996, 167, 108),
    ("c09 chroma",           24, 18, 3, 1, 1,  8, 1,  3,  2,  4,  4,      7,     -5, 0, 1,  15534, 182,  64),
    ("c10 w4-sharp",         24, 18, 3, 1, 1,  8, 0,  5,  5,  4,  8,      0,      9, 2, 2,  81628,  25,  63),
    ("c11 mixed-filt",       24, 18, 3, 1, 1,  8, 0,  6,  6,  8,  8,     11,     19, 1, 2, 262426, 139, 194),
    ("c12 10-bit",           16, 12, 1, 0, 0, 10, 0,  4,  4,  8,  8,     -3,      5, 0, 0, 873423, 219, 540),
    ("c13 12-bit",           16, 12, 1, 0, 0, 12, 0,  4,  4,  8,  8,     -3,      5, 0, 0, 873351, 219, 540),
    ("c14 extreme-neg",      24, 18, 3, 1, 1,  8, 0,  8,  8,  8,  8, -30000, -30000, 0, 0,      0,   0,   0),
    ("c14b extreme-pos",     24, 18, 3, 1, 1,  8, 0,  8,  8,  8,  8,  30000,  30000, 0, 0, 374400, 180, 180),
    ("c15 h4-remap",         24, 18, 3, 1, 1,  8, 0,  6,  6,  8,  4,      9,      0, 0, 0,  86793, 111,  64),
    ("c16 big-16x16",        48, 32, 3, 1, 1,  8, 0, 12,  9, 16, 16,    -27,     43, 0, 1, 4154216, 173, 164),
]

# NEW BILINEAR cases (filter index 3 on one or both axes). Chosen to witness, in order:
# both axes bilinear; each axis alone (mixed with an 8-tap on the other); the w<=4 and h<=4
# extents where a mis-ordered set-selection would silently fall into the 4-tap sets; chroma
# (subsampled MV); the edge clamp; and 10/12-bit rounding.
#           name              fw  fh  pl sx sy  bd  p   x   y   w   h  mvr  mvc  fx fy
BILINEAR_CASES = [
    ("b01 bilin hv",         24, 18, 3, 1, 1,  8, 0, 10,  8,  8,  8, -13,  21, 3, 3),
    ("b02 bilin h-only",     24, 18, 3, 1, 1,  8, 0,  8,  5,  8,  8,   0,   3, 3, 3),
    ("b03 bilin v-only",     24, 18, 3, 1, 1,  8, 0,  6,  4,  8,  8,   5,   0, 3, 3),
    ("b04 bilin integer",    24, 18, 3, 1, 1,  8, 0,  4,  3,  8,  8,   0,   0, 3, 3),
    ("b05 bilin-x eighttap-y", 24, 18, 3, 1, 1, 8, 0,  6,  6,  8,  8,  11,  19, 3, 0),
    ("b06 eighttap-x bilin-y", 24, 18, 3, 1, 1, 8, 0,  6,  6,  8,  8,  11,  19, 0, 3),
    ("b07 bilin w4",         24, 18, 3, 1, 1,  8, 0,  5,  5,  4,  8,   0,   9, 3, 3),
    ("b08 bilin h4",         24, 18, 3, 1, 1,  8, 0,  6,  6,  8,  4,   9,   0, 3, 3),
    ("b09 bilin 4x4",        24, 18, 3, 1, 1,  8, 0,  5,  5,  4,  4,   7,   9, 3, 3),
    ("b10 bilin chroma",     24, 18, 3, 1, 1,  8, 1,  3,  2,  4,  4,   7,  -5, 3, 3),
    ("b11 bilin tl-overhang", 24, 18, 3, 1, 1, 8, 0,  0,  0,  8,  8,  -9,  -7, 3, 3),
    ("b12 bilin 10-bit",     16, 12, 1, 0, 0, 10, 0,  4,  4,  8,  8,  -3,   5, 3, 3),
    ("b13 bilin 12-bit",     16, 12, 1, 0, 0, 12, 0,  4,  4,  8,  8,  -3,   5, 3, 3),
    ("b14 bilin 16x16",      48, 32, 3, 1, 1,  8, 0, 12,  9, 16, 16, -27,  43, 3, 3),
]


def main():
    import sys

    if len(sys.argv) > 1:
        rep = verify_against_spec(sys.argv[1])
        print("# verified embedded 6x16x8 table against spec md5 %s" % rep["md5"])
    else:
        print("# (pass the spec markdown path to re-verify the embedded table)")
    print("# bilinear_mc_ref.py — spec 7.11.3.4, spec md5 %s" % SPEC_MD5)
    print("# spec BILINEAR set %d -> drishti set %d" % (SPEC_BILINEAR_SET,
                                                        DRISHTI_BILINEAR_SET))

    print("\n# drishti set-5 rows (spec set 3 halved, phase 0 dropped):")
    for p, row in enumerate(drishti_rows(SPEC_BILINEAR_SET)):
        print("#   phase %2d: %s" % (p, row))

    print("\n# filter-set selection (BILINEAR is NOT remapped at any extent):")
    for dim in (2, 4, 5, 8):
        line = "#   dim %3d: " % dim
        for f in range(4):
            line += "filt%d->spec%d/dr%d  " % (f, filter_idx_spec(f, dim),
                                               filter_idx_drishti(f, dim))
        print(line)

    # --- SELF-VALIDATION against the 17 pre-existing goldens --------------------
    print("\n# self-validation vs the existing non-bilinear driver KATs:")
    bad = 0
    for row in EXISTING:
        (name, fw, fh, pl, sx, sy, bd, p, x, y, w, h, mvr, mvc, fx, fy,
         want_cs, want_first, want_last) = row
        cs, first, last = run_case(fw, fh, pl, sx, sy, bd, p, x, y, w, h, mvr, mvc, fx, fy)
        ok = (cs, first, last) == (want_cs, want_first, want_last)
        if not ok:
            bad += 1
            print("#   MISMATCH %-20s got (%d,%d,%d) want (%d,%d,%d)"
                  % (name, cs, first, last, want_cs, want_first, want_last))
    if bad:
        print("#   %d/%d MISMATCHED — this port is NOT trustworthy, stop." % (bad, len(EXISTING)))
        return 1
    print("#   all %d reproduced exactly — port validated." % len(EXISTING))

    print("\n# NEW BILINEAR known answers (paste into tests/av1_mc_driver.tcyr):")
    for (name, fw, fh, pl, sx, sy, bd, p, x, y, w, h, mvr, mvc, fx, fy) in BILINEAR_CASES:
        cs, first, last = run_case(fw, fh, pl, sx, sy, bd, p, x, y, w, h, mvr, mvc, fx, fy)
        print('    mcd_case("%s", %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %s, %s, %d, %d, %d, %d, %d);'
              % (name, fw, fh, pl, sx, sy, bd, p, x, y, w, h,
                 mvr if mvr >= 0 else "0 - %d" % -mvr,
                 mvc if mvc >= 0 else "0 - %d" % -mvc,
                 fx, fy, cs, first, last))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
